homeassistant:
  customize: !include customize.yaml
  name: IoT Dacha
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 201
  unit_system: metric
  time_zone: Europe/Minsk
#  external_url: "https://naliboki.tech"
#  internal_url: "https://192.168.1.105:8123"
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 178.124.206.28/32
        - 82.209.247.130/32
  allowlist_external_dirs:
    - "/tmp"
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml


mqtt:
## Выбрать один из вариантов для брокера!  
  broker: core-mosquitto  # Локальный брокер
  #broker: IP adress  # Внешний брокер
  discovery: true
  discovery_prefix: homeassistant  
  username: toresmqtt
  password: 1q2wTores3e4r@