- platform: nut
  name: "Poverex VI 2000 LED"
  host: a0d7b954-nut
  username: root
  password: 1q2wtores3e4r
  resources:
    - battery.charge
    - battery.voltage
    - input.voltage
    - output.voltage
    - ups.load
    - ups.status
